input:
  file: /Users/abigot/CLINM/Calibration/CNAO_0425/Run_06_Config1.root
  tree:
    name: tree
    branches: [
      pl0ntu.fPlAmplitude,
      pl0ntu.fPlCharge,
      pl1ntu.fPlAmplitude,
      pl1ntu.fPlCharge
    ]

histogram_config:
  name: [
    Pl0Amplitude,
    Pl0Charge,
    Pl1Amplitude,
    Pl1Charge
  ]
  nbin: [
    200,
    200,
    200,
    200
  ]

fit:
  range: [
    [3, 14],
    [20, 240],
    [5, 13],
    [60, 220]
  ]
  pars:
    MPV_landau: [
      [7, 5, 9],
      [90, 60, 105],
      [9, 7, 10],
      [130, 110, 140]
    ]
    sigma_landau: [
      [0.1, 0.01, 10],
      [10, 0.01, 1000],
      [0.1, 0.01, 10],
      [10, 0.1, 1000]
    ]
    mu_gauss: [
      [0, -1, 6],
      [0, -10, 150],
      [0, -1, 15],
      [0, -10, 150]
    ]
    sigma_gauss: [
      [1, 0.05, 10],
      [5, 0.1, 30],
      [1, 0.05, 10],
      [10, 0.1, 40]
    ]
    norm: [
      [2000, 1.0, 1000000],
      [2000, 1.0, 1000000],
      [2500, 1.0, 1000000],
      [20000, 1.0, 1000000]
    ]

output:
  file: FitResults/RealData/fit_result_CNAO0425_Run6_Config1.root
  plot:
    activate: True
    label: [
      Amplitude of Plastic 1 (mV),
      Charge of Plastic 1 (mV.s),
      Amplitude of Plastic 2 (mV),
      Charge of Plastic 2 (mV.s)
    ]
    ymin: [
      0,
      0,
      0,
      0
    ]
    ymax: [
      "auto",
      "auto",
      "auto",
      "auto"
    ]
    info:
      exp: CLINM
      campaign: CNAO April 2025
      beam:
        particle: ^{12}C
        energy: "79.84 MeV/u"
      run: 6