command:
  print: True
  run: False

STIVI:
  Reconstruction_dir: /Users/abigot/SHOE/main/Reconstruction

DecodeWC:
  input: [file1, file2]
  output:
    name: auto # auto or file name
    merge: True  # True or False
  exp: CLINM2025
  run: 1  # single value (if all files are from same run) or list matching input entries
  flat: [True, False] # True or False