source:
    energy: 23.71  # in MeV
    n: 100000

campaign: CYRCE0425
run: "16_Config1"

width:
    wheel: 2.156 # mm
    collimator: 24 # mm
    plastic1: 2 # mm
    plastic2: 4 # mm

output:
    dir: /Users/abigot/CLINM-AF/Calibration/Simulation/SimResultsRaw